# Base configs
baseurl: ""

# UI configs
title: "Abhishek Pandey"
name: "Abhishek Pandey"
bio: "A Player"
social_urls:
  facebook: "https://www.facebook.com/abhishekpandey"
  twitter: "https://www.twitter.com/abhi4064"
  instagram: "https://www.instagram.com/iamabhiiiii"
